<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RestoreSources></RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\PromptTool\\PromptTool.csproj" />
    <ProjectReference Include="..\\PromptTool.Core\\PromptTool.Core.csproj" />
  </ItemGroup>
</Project>
